feat: add --all flag to av commit amend
aviator-co/av pull request #452
Opened 2024-11-08 15:07 UTC by dacuna-ic

Adds the --flag to `av commit amend` to match `av commit create`

2024-11-08 21:55 UTC, draftcode requested changes

2024-11-08 21:55 UTC, draftcode commented on cmd/av/commit_amend.go
> +	if commitCreateFlags.All {
I think this should be commitAmendFlags

2024-11-08 21:55 UTC, draftcode commented on cmd/av/commit_amend.go
> +	commitCreateCmd.Flags().
This should be commitAmendCmd.

2024-11-09 19:53 UTC, dacuna-ic commented
@draftcode should be good now! sorry for that, just copied stuff in a rush and didn't pay much attention 😅

2024-11-11 18:00 UTC, merged